osx_image: xcode10.1
language: swift
os: osx
xcode_project: Nova.xcodeproj
xcode_scheme: Nova
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
script:
- set -o pipefail
- xcodebuild build -workspace Nova.xcworkspace -scheme "Nova" -sdk iphonesimulator | xcpretty
